-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- resize splits if window got resized
-- vim.api.nvim_create_autocmd({ "FlutterDevices" }, {
--   command = "FlutterDevices",
-- })

-- -- resize splits if window got resized
-- vim.api.nvim_create_autocmd({ "VimResized" }, {
--   callback = function()
--     vim.cmd("tabdo wincmd =")
--   end,
-- })
--
-- -- resize splits if window got resized
-- vim.api.nvim_create_autocmd({ "VimResized" }, {
--   callback = function()
--     vim.cmd("tabdo wincmd =")
--   end,
-- })
--
-- -- Fixes Autocomment
-- vim.api.nvim_create_autocmd("BufEnter", {
--   pattern = "*",
--   command = "set fo-=c fo-=r fo-=o",
-- })
--
-- -- close some filetypes with <q>
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = {
--     "dap-float",
--     "httpResult",
--   },
--   callback = function(event)
--     vim.bo[event.buf].buflisted = false
--     vim.keymap.set("n", "q", "<cmd>close<cr>", { buffer = event.buf, silent = true })
--   end,
-- })
--
-- -- close some filetypes with <q>
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = {
--     "dap-terminal",
--   },
--   callback = function(event)
--     vim.keymap.set("n", "q", "<cmd>bdelete!<cr>", { buffer = event.buf, silent = true })
--   end,
-- })
